#!/usr/bin/env bash
# Auto-populate terraform.tfvars from the OCI CLI + local config.
#
# Pulls: tenancy_ocid & region (from ~/.oci/config), availability_domain and
# instance_image_ocid (from `oci`), ssh_public_key (from ~/.ssh), and generates
# a fresh encryption_key. compartment_ocid defaults to the tenancy root unless
# you pass --compartment <ocid>.
#
# Usage:
#   ./gen-tfvars.sh [--profile DEFAULT] [--compartment <ocid>] [--domain freeai.punkadillo.com] [--force]
#
# Requires: oci CLI configured, jq, and node OR openssl (for the key).
set -euo pipefail

PROFILE="DEFAULT"
COMPARTMENT=""
DOMAIN="freeai.punkadillo.com"
FORCE=0
OUT="terraform.tfvars"
CONFIG="${OCI_CLI_CONFIG_FILE:-$HOME/.oci/config}"

while [ $# -gt 0 ]; do
  case "$1" in
    --profile)     PROFILE="$2"; shift 2 ;;
    --compartment) COMPARTMENT="$2"; shift 2 ;;
    --domain)      DOMAIN="$2"; shift 2 ;;
    --force)       FORCE=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

command -v oci >/dev/null || { echo "oci CLI not found" >&2; exit 1; }
command -v jq  >/dev/null || { echo "jq not found" >&2; exit 1; }
[ -f "$CONFIG" ] || { echo "OCI config not found at $CONFIG" >&2; exit 1; }

if [ -f "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "$OUT already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

# --- read tenancy + region from the chosen config profile ---------------------
section() { awk -v p="[$1]" '$0==p{f=1;next} /^\[/{f=0} f' "$CONFIG"; }
val()     { section "$1" | awk -F'=' -v k="$2" '$1 ~ k {sub(/^[^=]*=/,""); gsub(/ /,""); print; exit}'; }

TENANCY="$(val "$PROFILE" '^tenancy')"
REGION="$(val "$PROFILE" '^region')"
[ -n "$TENANCY" ] || { echo "no tenancy in profile [$PROFILE]" >&2; exit 1; }
[ -n "$REGION" ]  || { echo "no region in profile [$PROFILE]" >&2; exit 1; }
COMPARTMENT="${COMPARTMENT:-$TENANCY}"

echo ">> profile=$PROFILE region=$REGION" >&2
echo ">> compartment=$COMPARTMENT" >&2

# --- availability domain (first one with A1 is a guess; switch if Out of capacity)
AD="$(oci iam availability-domain list --profile "$PROFILE" \
  --compartment-id "$TENANCY" --query 'data[0].name' --raw-output)"
echo ">> availability_domain=$AD" >&2

# --- latest Ubuntu 22.04 aarch64 image for A1 ---------------------------------
IMAGE="$(oci compute image list --profile "$PROFILE" \
  --compartment-id "$COMPARTMENT" \
  --operating-system "Canonical Ubuntu" --operating-system-version "22.04" \
  --shape "VM.Standard.A1.Flex" --sort-by TIMECREATED --sort-order DESC \
  --query 'data[0].id' --raw-output)"
[ -n "$IMAGE" ] && [ "$IMAGE" != "null" ] || { echo "no Ubuntu 22.04 A1 image found in $REGION" >&2; exit 1; }
echo ">> instance_image_ocid=$IMAGE" >&2

# --- SSH public key (first ed25519, else rsa) ---------------------------------
SSH_PUB=""
for f in "$HOME/.ssh/id_ed25519.pub" "$HOME/.ssh/id_rsa.pub"; do
  [ -f "$f" ] && { SSH_PUB="$(cat "$f")"; break; }
done
[ -n "$SSH_PUB" ] || { echo "no SSH public key in ~/.ssh (id_ed25519.pub / id_rsa.pub)" >&2; exit 1; }

# --- encryption key -----------------------------------------------------------
if command -v node >/dev/null; then
  ENC_KEY="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
else
  ENC_KEY="$(openssl rand -hex 32)"
fi

# --- write terraform.tfvars ---------------------------------------------------
cat > "$OUT" <<TFVARS
# Generated by gen-tfvars.sh on profile [$PROFILE]. gitignored.
tenancy_ocid     = "$TENANCY"
compartment_ocid = "$COMPARTMENT"
region           = "$REGION"

availability_domain = "$AD"

ssh_public_key = "$SSH_PUB"

# lb_ingress_cidrs = ["203.0.113.10/32"]   # Phase 9: lock to your IPs

instance_image_ocid = "$IMAGE"
instance_ocpus      = 1
instance_memory_gb  = 6

app_image = "ghcr.io/tashfeenahmed/freellmapi:latest"

# BACK THIS UP — it decrypts every stored provider key.
encryption_key = "$ENC_KEY"

# ghcr_username   = "tashfeenahmed"   # only if the GHCR package is private
# ghcr_pull_token = "ghp_xxx"

enable_https = false
domain_name  = "$DOMAIN"
TFVARS

chmod 600 "$OUT"
echo ">> wrote $OUT (mode 600)" >&2
echo ">> review it, then: terraform init && terraform plan" >&2
