// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: jimesh/jimesh.proto

package jimeshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	JiMesh_ListModels_FullMethodName    = "/jimesh.v1.JiMesh/ListModels"
	JiMesh_SyncCatalog_FullMethodName   = "/jimesh.v1.JiMesh/SyncCatalog"
	JiMesh_ListChains_FullMethodName    = "/jimesh.v1.JiMesh/ListChains"
	JiMesh_UpsertChain_FullMethodName   = "/jimesh.v1.JiMesh/UpsertChain"
	JiMesh_Route_FullMethodName         = "/jimesh.v1.JiMesh/Route"
	JiMesh_StreamEvents_FullMethodName  = "/jimesh.v1.JiMesh/StreamEvents"
	JiMesh_StreamScores_FullMethodName  = "/jimesh.v1.JiMesh/StreamScores"
	JiMesh_StreamHealth_FullMethodName  = "/jimesh.v1.JiMesh/StreamHealth"
	JiMesh_GetScores_FullMethodName     = "/jimesh.v1.JiMesh/GetScores"
	JiMesh_ListProviders_FullMethodName = "/jimesh.v1.JiMesh/ListProviders"
	JiMesh_CheckHealth_FullMethodName   = "/jimesh.v1.JiMesh/CheckHealth"
	JiMesh_CostReport_FullMethodName    = "/jimesh.v1.JiMesh/CostReport"
)

// JiMeshClient is the client API for JiMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JiMeshClient interface {
	// Catalog
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	SyncCatalog(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Chains
	ListChains(ctx context.Context, in *ListChainsRequest, opts ...grpc.CallOption) (*ListChainsResponse, error)
	UpsertChain(ctx context.Context, in *UpsertChainRequest, opts ...grpc.CallOption) (*UpsertChainResponse, error)
	// Routing (fast path)
	Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteDecision, error)
	// Realtime — backed by Redis Streams consumer groups
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (JiMesh_StreamEventsClient, error)
	StreamScores(ctx context.Context, in *StreamScoresRequest, opts ...grpc.CallOption) (JiMesh_StreamScoresClient, error)
	StreamHealth(ctx context.Context, in *StreamHealthRequest, opts ...grpc.CallOption) (JiMesh_StreamHealthClient, error)
	// Analytics / Providers
	GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error)
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*ProviderHealth, error)
	CostReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type jiMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewJiMeshClient(cc grpc.ClientConnInterface) JiMeshClient {
	return &jiMeshClient{cc}
}

func (c *jiMeshClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, JiMesh_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) SyncCatalog(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, JiMesh_SyncCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) ListChains(ctx context.Context, in *ListChainsRequest, opts ...grpc.CallOption) (*ListChainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChainsResponse)
	err := c.cc.Invoke(ctx, JiMesh_ListChains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) UpsertChain(ctx context.Context, in *UpsertChainRequest, opts ...grpc.CallOption) (*UpsertChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertChainResponse)
	err := c.cc.Invoke(ctx, JiMesh_UpsertChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) Route(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteDecision)
	err := c.cc.Invoke(ctx, JiMesh_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (JiMesh_StreamEventsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JiMesh_ServiceDesc.Streams[0], JiMesh_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &jiMeshStreamEventsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JiMesh_StreamEventsClient interface {
	Recv() (*RouteEvent, error)
	grpc.ClientStream
}

type jiMeshStreamEventsClient struct {
	grpc.ClientStream
}

func (x *jiMeshStreamEventsClient) Recv() (*RouteEvent, error) {
	m := new(RouteEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jiMeshClient) StreamScores(ctx context.Context, in *StreamScoresRequest, opts ...grpc.CallOption) (JiMesh_StreamScoresClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JiMesh_ServiceDesc.Streams[1], JiMesh_StreamScores_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &jiMeshStreamScoresClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JiMesh_StreamScoresClient interface {
	Recv() (*ScoreSnapshot, error)
	grpc.ClientStream
}

type jiMeshStreamScoresClient struct {
	grpc.ClientStream
}

func (x *jiMeshStreamScoresClient) Recv() (*ScoreSnapshot, error) {
	m := new(ScoreSnapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jiMeshClient) StreamHealth(ctx context.Context, in *StreamHealthRequest, opts ...grpc.CallOption) (JiMesh_StreamHealthClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JiMesh_ServiceDesc.Streams[2], JiMesh_StreamHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &jiMeshStreamHealthClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JiMesh_StreamHealthClient interface {
	Recv() (*ProviderHealth, error)
	grpc.ClientStream
}

type jiMeshStreamHealthClient struct {
	grpc.ClientStream
}

func (x *jiMeshStreamHealthClient) Recv() (*ProviderHealth, error) {
	m := new(ProviderHealth)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jiMeshClient) GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScoresResponse)
	err := c.cc.Invoke(ctx, JiMesh_GetScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, JiMesh_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*ProviderHealth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderHealth)
	err := c.cc.Invoke(ctx, JiMesh_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiMeshClient) CostReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, JiMesh_CostReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JiMeshServer is the server API for JiMesh service.
// All implementations must embed UnimplementedJiMeshServer
// for forward compatibility
type JiMeshServer interface {
	// Catalog
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	SyncCatalog(context.Context, *SyncRequest) (*SyncResponse, error)
	// Chains
	ListChains(context.Context, *ListChainsRequest) (*ListChainsResponse, error)
	UpsertChain(context.Context, *UpsertChainRequest) (*UpsertChainResponse, error)
	// Routing (fast path)
	Route(context.Context, *RouteRequest) (*RouteDecision, error)
	// Realtime — backed by Redis Streams consumer groups
	StreamEvents(*StreamEventsRequest, JiMesh_StreamEventsServer) error
	StreamScores(*StreamScoresRequest, JiMesh_StreamScoresServer) error
	StreamHealth(*StreamHealthRequest, JiMesh_StreamHealthServer) error
	// Analytics / Providers
	GetScores(context.Context, *GetScoresRequest) (*GetScoresResponse, error)
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	CheckHealth(context.Context, *CheckHealthRequest) (*ProviderHealth, error)
	CostReport(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedJiMeshServer()
}

// UnimplementedJiMeshServer must be embedded to have forward compatible implementations.
type UnimplementedJiMeshServer struct {
}

func (UnimplementedJiMeshServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedJiMeshServer) SyncCatalog(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncCatalog not implemented")
}
func (UnimplementedJiMeshServer) ListChains(context.Context, *ListChainsRequest) (*ListChainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChains not implemented")
}
func (UnimplementedJiMeshServer) UpsertChain(context.Context, *UpsertChainRequest) (*UpsertChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertChain not implemented")
}
func (UnimplementedJiMeshServer) Route(context.Context, *RouteRequest) (*RouteDecision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedJiMeshServer) StreamEvents(*StreamEventsRequest, JiMesh_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedJiMeshServer) StreamScores(*StreamScoresRequest, JiMesh_StreamScoresServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamScores not implemented")
}
func (UnimplementedJiMeshServer) StreamHealth(*StreamHealthRequest, JiMesh_StreamHealthServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHealth not implemented")
}
func (UnimplementedJiMeshServer) GetScores(context.Context, *GetScoresRequest) (*GetScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScores not implemented")
}
func (UnimplementedJiMeshServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedJiMeshServer) CheckHealth(context.Context, *CheckHealthRequest) (*ProviderHealth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedJiMeshServer) CostReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CostReport not implemented")
}
func (UnimplementedJiMeshServer) mustEmbedUnimplementedJiMeshServer() {}

// UnsafeJiMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JiMeshServer will
// result in compilation errors.
type UnsafeJiMeshServer interface {
	mustEmbedUnimplementedJiMeshServer()
}

func RegisterJiMeshServer(s grpc.ServiceRegistrar, srv JiMeshServer) {
	s.RegisterService(&JiMesh_ServiceDesc, srv)
}

func _JiMesh_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_SyncCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).SyncCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_SyncCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).SyncCatalog(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_ListChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).ListChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_ListChains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).ListChains(ctx, req.(*ListChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_UpsertChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).UpsertChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_UpsertChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).UpsertChain(ctx, req.(*UpsertChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).Route(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JiMeshServer).StreamEvents(m, &jiMeshStreamEventsServer{ServerStream: stream})
}

type JiMesh_StreamEventsServer interface {
	Send(*RouteEvent) error
	grpc.ServerStream
}

type jiMeshStreamEventsServer struct {
	grpc.ServerStream
}

func (x *jiMeshStreamEventsServer) Send(m *RouteEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _JiMesh_StreamScores_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamScoresRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JiMeshServer).StreamScores(m, &jiMeshStreamScoresServer{ServerStream: stream})
}

type JiMesh_StreamScoresServer interface {
	Send(*ScoreSnapshot) error
	grpc.ServerStream
}

type jiMeshStreamScoresServer struct {
	grpc.ServerStream
}

func (x *jiMeshStreamScoresServer) Send(m *ScoreSnapshot) error {
	return x.ServerStream.SendMsg(m)
}

func _JiMesh_StreamHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JiMeshServer).StreamHealth(m, &jiMeshStreamHealthServer{ServerStream: stream})
}

type JiMesh_StreamHealthServer interface {
	Send(*ProviderHealth) error
	grpc.ServerStream
}

type jiMeshStreamHealthServer struct {
	grpc.ServerStream
}

func (x *jiMeshStreamHealthServer) Send(m *ProviderHealth) error {
	return x.ServerStream.SendMsg(m)
}

func _JiMesh_GetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).GetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_GetScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).GetScores(ctx, req.(*GetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiMesh_CostReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiMeshServer).CostReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiMesh_CostReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiMeshServer).CostReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JiMesh_ServiceDesc is the grpc.ServiceDesc for JiMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JiMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jimesh.v1.JiMesh",
	HandlerType: (*JiMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _JiMesh_ListModels_Handler,
		},
		{
			MethodName: "SyncCatalog",
			Handler:    _JiMesh_SyncCatalog_Handler,
		},
		{
			MethodName: "ListChains",
			Handler:    _JiMesh_ListChains_Handler,
		},
		{
			MethodName: "UpsertChain",
			Handler:    _JiMesh_UpsertChain_Handler,
		},
		{
			MethodName: "Route",
			Handler:    _JiMesh_Route_Handler,
		},
		{
			MethodName: "GetScores",
			Handler:    _JiMesh_GetScores_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _JiMesh_ListProviders_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _JiMesh_CheckHealth_Handler,
		},
		{
			MethodName: "CostReport",
			Handler:    _JiMesh_CostReport_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _JiMesh_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamScores",
			Handler:       _JiMesh_StreamScores_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamHealth",
			Handler:       _JiMesh_StreamHealth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jimesh/jimesh.proto",
}
